// findTheDifference
/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*/


class Solution {
    public char findTheDifference(String s, String t) {
        
        int result = 0;
        
        for(int i : t.toCharArray()){
            result += i;
        }
        
        for(int j : s.toCharArray()){
            
                result -= j;
            
        }
        
        return (char) result;
        
    }
}

